apiVersion: database.wufan/v1
kind: Mysql
metadata:
  labels:
    app.kubernetes.io/name: axe-dmp
    app.kubernetes.io/managed-by: kustomize
  name: mysql-axe
spec:
  replica: 3
  mysql:
    mysqlimage: "mysql:8.0.32"
    rootPassword: "axe_operator"
    mysqlUser: "axe"
    mysqlPassword: "123456"
    resources :
      requests:
        cpu: "1024m"
        memory: "256Mi"
      limits:
        cpu: "2048m"
        memory: "2Gi"
  router:
    replica: 1
    routerimage: "mysql/mysql-router:latest"
    resources :
      requests:
        cpu: "1024m"
        memory: "256Mi"
      limits:
        cpu: "2048m"
        memory: "2Gi"