apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: axe-dmp-controller-manager-cluster-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch