apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: axe-dmp-controller-manager-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: axe-dmp-controller-manager
  namespace: axe-dmp-system
roleRef:
  kind: ClusterRole
  name: axe-dmp-controller-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io